name: zinkwazi_lagoon_lodge_app
description: Zinkwazi Lagoon Lodge App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Date Time
  intl: ^0.16.1

  # Local Storage
  hive: ^1.4.3
  hive_flutter: ^0.3.1

  # Networking
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  socket_io_client: ^0.9.11

  # Notification (check docs for release build for PRO Guard)
  flutter_local_notifications: ^3.0.3

  # Staggered Grid View
  flutter_staggered_grid_view: ^0.3.2

  # Service Locator
  get_it: ^5.0.4

  # State Management
  provider: ^4.1.3

  # Util
  cupertino_icons: ^1.0.2
  equatable: ^1.2.0
  dartz: ^0.9.1
  collection: any

  # Web View
  webview_flutter: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  hive_generator: ^0.8.2
  build_runner: ^1.10.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/