version: "3.9"
services:
  # POSTGRES DATABASE
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DATABASE}"
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data


  # REDIS CACHE
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/var/lib/redis


  # API NODEJS SERVER
  api:
    #image: docker.pkg.github.com/donk3ys/docker-images/zink-api
    image: zink-api
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "${NODE_ENV}"
      EXPRESS_PORT: "${EXPRESS_PORT}"
      JWT_SECERET: "${JWT_SECERET}"
      JWT_ACCESS_TIME: "${JWT_ACCESS_TIME}"
      JWT_REFRESH_TIME: "${JWT_REFRESH_TIME}"
      PGHOST: db
      PGUSER: "${PG_USER}"
      PGPASSWORD: "${PG_PASSWORD}"
      PGDATABASE: "${PG_DATABASE}"
      PGPORT: "${PG_PORT}"
      REDIS_HOST: cache
      REDIS_PORT: "${REDIS_PORT}"
    depends_on:
      - cache
      - db


  # ADMIN FLUTTER WEB-PORTAL
  web-admin:
    #image: docker.pkg.github.com/donk3ys/docker-images/zink-web-admin
    image: zink-web-admin
    ports:
      - "8000:8000"
    #restart: always
    depends_on:
      - api


  # REVERSE PROXY NGINX GATEWAY
  ingress:
    #image: docker.pkg.github.com/donk3ys/docker-images/zink-ingress
    image: zink-ingress
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web-admin
    restart: always
    #    volumes:
    #      - ./dhparam:/etc/nginx/dhparam
    #      - ./certbot/conf/:/etc/nginx/ssl/
    #      - ./certbot/data:/usr/share/nginx/html/letsencrypt
